"use client";

// Settings · Smart Alerts Center.
//
// One compact list. Every row is auto-generated by the existing
// engine detectors (composed in src/lib/alerts.ts). No filters,
// no manual settings, no CRUD. Tap a row → BottomSheet with a
// slightly deeper explanation.

import { useMemo, useState } from "react";
import { AnimatePresence, motion, useReducedMotion } from "framer-motion";
import {
  AlertTriangle,
  ArrowUpRight,
  BadgeCheck,
  Bell,
  CalendarClock,
  CreditCard,
  FlagTriangleRight,
  HandCoins,
  Landmark,
  Sparkles,
  TrendingDown,
  TrendingUp,
  Wallet,
  type LucideIcon,
} from "lucide-react";

import { BottomSheet } from "@/components/ui/bottom-sheet";
import { useFinanceStore } from "@/lib/store";
import { currentMonthKey } from "@/lib/dates";
import { buildSmartAlerts, type AlertKind, type SmartAlert } from "@/lib/alerts";
import { tap as hapticTap } from "@/lib/haptics";

const EASE = [0.32, 0.72, 0, 1] as const;

const ICON: Record<AlertKind, LucideIcon> = {
  eom: TrendingUp,
  pace: TrendingDown,
  budget: Wallet,
  overdraft: AlertTriangle,
  anomaly: FlagTriangleRight,
  subs: Sparkles,
  pressure: CalendarClock,
  "loan-final": BadgeCheck,
  "charge-upcoming": CalendarClock,
  "installment-final": BadgeCheck,
  "income-received": HandCoins,
  "credit-limit": CreditCard,
};

export function AlertsCenter() {
  const hydrated = useFinanceStore((s) => s.hasHydrated);
  const accounts = useFinanceStore((s) => s.accounts);
  const loans = useFinanceStore((s) => s.loans);
  const incomes = useFinanceStore((s) => s.incomes);
  const rules = useFinanceStore((s) => s.rules);
  const statuses = useFinanceStore((s) => s.statuses);
  const entries = useFinanceStore((s) => s.entries);
  const monthlyBudget = useFinanceStore((s) => s.monthlyBudget);

  const monthKey = currentMonthKey();
  const alerts = useMemo(() => {
    if (!hydrated) return [];
    return buildSmartAlerts({
      accounts,
      loans,
      incomes,
      rules,
      statuses,
      entries,
      monthlyBudget,
      monthKey,
    });
  }, [
    hydrated,
    accounts,
    loans,
    incomes,
    rules,
    statuses,
    entries,
    monthlyBudget,
    monthKey,
  ]);

  const [openId, setOpenId] = useState<string | null>(null);
  const active = alerts.find((a) => a.id === openId) ?? null;
  const reduced = useReducedMotion();

  const total = alerts.length;
  const important = alerts.filter((a) => a.level === "important").length;

  function openAlert(id: string) {
    hapticTap();
    setOpenId(id);
  }

  return (
    <div className="ac-mini" dir="rtl">
      <div className="ac-header">
        <div className="ac-header-icon" aria-hidden>
          <Bell className="size-4" />
        </div>
        <div className="ac-header-text">
          <span className="ac-header-title">מרכז התראות חכם</span>
          <span className="ac-header-sub">
            {total === 0
              ? "אין התראות פעילות · הכל תקין"
              : `${total} התראות פעילות`}
          </span>
        </div>
        <div className="ac-header-badges" aria-hidden>
          <span className="ac-badge ac-badge-total">{total}</span>
          {important > 0 ? (
            <span className="ac-badge ac-badge-important" title="חשובות">
              {important}
            </span>
          ) : null}
        </div>
      </div>

      {alerts.length === 0 ? (
        <div className="ac-empty">
          <span className="ac-empty-icon" aria-hidden>
            <BadgeCheck className="size-5" strokeWidth={1.6} />
          </span>
          <p className="ac-empty-title">שקט מוחלט</p>
          <p className="ac-empty-body">
            המערכת לא זיהתה סטייה, חריגה או חיוב חריג הדורש תשומת לב.
          </p>
        </div>
      ) : (
        <ul className="ac-list">
          <AnimatePresence initial={false}>
            {alerts.map((a, idx) => (
              <motion.li
                key={a.id}
                layout
                initial={reduced ? { opacity: 0 } : { opacity: 0, y: 4 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{
                  delay: idx * 0.03,
                  duration: reduced ? 0.12 : 0.32,
                  ease: EASE,
                }}
              >
                <AlertRow alert={a} onClick={() => openAlert(a.id)} />
              </motion.li>
            ))}
          </AnimatePresence>
        </ul>
      )}

      <BottomSheet
        open={active !== null}
        onOpenChange={(o) => {
          if (!o) setOpenId(null);
        }}
        title={active?.title ?? "התראה"}
        className="ac-sheet"
      >
        {active ? <AlertDetail alert={active} /> : null}
      </BottomSheet>
    </div>
  );
}

function AlertRow({
  alert,
  onClick,
}: {
  alert: SmartAlert;
  onClick: () => void;
}) {
  const Icon = ICON[alert.kind] ?? Landmark;
  return (
    <button
      type="button"
      onClick={onClick}
      className="ac-row"
      data-tone={alert.tone}
      aria-label={alert.title}
    >
      <span aria-hidden className="ac-row-icon">
        <Icon className="size-4" strokeWidth={1.7} />
      </span>
      <span className="ac-row-body">
        <span className="ac-row-title">{alert.title}</span>
        <span className="ac-row-detail">{alert.detail}</span>
      </span>
      <span aria-hidden className="ac-row-chev">
        <ArrowUpRight className="size-3.5" />
      </span>
    </button>
  );
}

function AlertDetail({ alert }: { alert: SmartAlert }) {
  const Icon = ICON[alert.kind] ?? Landmark;
  return (
    <div className="ac-detail" dir="rtl">
      <div className="ac-detail-head" data-tone={alert.tone}>
        <span aria-hidden className="ac-detail-icon">
          <Icon className="size-5" strokeWidth={1.7} />
        </span>
        <div className="ac-detail-titles">
          <span className="ac-detail-title">{alert.title}</span>
          <span className="ac-detail-sub">{alert.detail}</span>
        </div>
      </div>
      <div className="ac-detail-body">
        {alert.body.map((line, idx) => (
          <p key={idx} className="ac-detail-line">
            {line}
          </p>
        ))}
      </div>
    </div>
  );
}
